import { Inter } from "next/font/google";
import "./globals.css";
import FunctionDataContex from "./context/contextData";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="#" />
      </head>

      <body className={inter.className}>
        <FunctionDataContex>{children}</FunctionDataContex>
      </body>
    </html>
  );
}
